[package]
name = "phrase-rs"
version = "0.1.0"
authors = ["Stuart Axelbrooke <stuart@axelbrooke.com>"]
edition = "2018"

[dependencies]

rocket = "0.4"
rusqlite = "0.18"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rust-stemmers = "1.1"
clap = "2.33"
log = "0.4"
env_logger = "0.6"
regex = "1"

[dependencies.rocket_contrib]
version = "0.4.0"
default-features = false
features = ["json"]
